variables:
  COMPONENT: 'catalogue'


resources:
  repositories:
    - repository: templates
      type: github
      name: GurukaYadav/roboshop-azure-devops-templates

jobs:
  - template: nodejs.yml@templates